import React from 'react';
import { TextProps as TextBaseProps, Animated, StyleProp, TextStyle } from 'react-native';
export declare type TextProps = TextBaseProps & {
    weight?: '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900' | 'bold';
    size?: number;
    variant?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'subtitle1' | 'subtitle2' | 'body1' | 'body2' | 'caption' | 'button' | 'overline';
    color?: Animated.Value | 'primary' | 'secondary' | string;
    contrast?: number | boolean;
    dense?: boolean;
    animated?: boolean;
    gutterBottom?: number;
    letterSpacing?: number;
    style?: StyleProp<TextStyle>;
    children?: any;
    align?: 'center' | 'left' | 'right' | 'justify';
    transform?: 'uppercase' | 'lowercase' | 'capitalize' | 'none';
    theme?: any;
};
declare const Text: React.FC<TextProps>;
export default Text;
